services:
  - type: web
    name: progresswatch
    runtime: docker
    plan: 0.5c-512mb
    healthCheckPath: /up
    envVars:
      - fromGroup: progresswatch
      - key: DATABASE_URL
        fromDatabase:
          name: progresswatch-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: keyvalue
          name: progresswatch-keyvalue
          property: connectionString
      - key: SIDEKIQ_REDIS_URL
        fromService:
          type: keyvalue
          name: progresswatch-keyvalue
          property: connectionString

  - type: keyvalue
    name: progresswatch-keyvalue
    plan: free
    maxmemoryPolicy: noeviction
    ipAllowList: []

databases:
  - name: progresswatch-db
    plan: 0.1c-256mb
    diskSizeGB: 1

envVarGroups:
  - name: progresswatch
    envVars:
      - key: SECRET_KEY_BASE
        generateValue: true
      - key: FORCE_SSL
        value: true
      - key: VAPID_PUBLIC_KEY
        sync: false
      - key: VAPID_PRIVATE_KEY
        sync: false
